service: my-sls-service

provider:
  name: aws
  runtime: python3.7
  stackName: lambda-${self:service.name}
  tag: ${opt:tag}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::somebucket/*"

functions:
  myFunc:
    name: myFunc
    tags:
      RESOURCE: lambda
      PUBLIC: false
      yor_trace: 6e81cc0c-c3dc-4c11-8e14-2d89fa868963
      git_org: jamcg
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "*"
        Resource:
          - "*"
    handler: Handler.handle
    timeout: 600
    memorySize: 320